name: Robot Framework Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    env: 
      USERNAME: ${{ secrets.username }}
      PASSWORD: ${{ secrets.password }}
      BASE_URL: ${{ secrets.URL }}

    steps:
      # Checkout code
      - name: Checkout repo
        uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'


      # Create virtualenv & install dependencies
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -U pip
          pip install -r requirements.txt

      # Run Robot tests
      - name: Run Robot Framework tests
        run: |
          source .venv/bin/activate
          robot --outputdir Results TestCases/

      # Upload results as artifacts
      - name: Upload Robot Results
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: Results/
