name: Robot Framework Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    env: 
      USERNAME: standard_user
      PASSWORD: secret_sauce
      URL: https://www.saucedemo.com

    steps:
      # Checkout code
      - name: Checkout repo
        uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'


      # Create virtualenv & install dependencies
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -U pip
          pip install -r requirements.txt

      # Run Robot tests
      - name: Run Robot Framework tests
        run: |
          source .venv/bin/activate
          robot --outputdir Results TestCases/

      # Upload results as artifacts
      - name: Upload Robot Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: Results/


      # 📩 Send email with attached results
      - name: Send report by email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: omarfares802@gmail.com
          password: oode dukn dxxf ctal
          subject: "Robot Framework Test Results"
          to: "omar-fares@outlook.sa"
          from: "Robot CI omar fares"
          body: "Attached are the latest Robot Framework test reports."
          attachments: "Results/log.html,Results/report.html"